DELETE
FROM ROUTE;
DELETE
FROM CITY;

INSERT INTO CITY
values (1, 'Zaragoza');
INSERT INTO CITY
values (2, 'Barcelona');
INSERT INTO CITY
values (3, 'Oviedo');
INSERT INTO CITY
values (4, 'Madrid');
INSERT INTO CITY
values (5, 'Malaga');
INSERT INTO CITY
values (6, 'Sevilla');
INSERT INTO CITY
values (7, 'Paris');
INSERT INTO CITY
values (8, 'London');
INSERT INTO CITY
values (9, 'Munich');
INSERT INTO CITY
values (10, 'Milan');
INSERT INTO CITY
values (11, 'Torino');
INSERT INTO CITY
values (12, 'Geneva');
INSERT INTO CITY
values (13, 'Zagreb');
INSERT INTO CITY
values (14, 'Oslo');
INSERT INTO CITY
values (15, 'Gothenburg');
INSERT INTO CITY
values (16, 'Stockholm');
INSERT INTO CITY
values (17, 'Tallinn');
INSERT INTO CITY
values (18, 'New York');
INSERT INTO CITY
values (19, 'Los Angeles');
INSERT INTO CITY
values (20, 'Tokyo');

INSERT INTO ROUTE
values (1, PARSEDATETIME('11:44', 'HH:mm'), PARSEDATETIME('12:49', 'HH:mm'), 1, 2);
INSERT INTO ROUTE
values (2, PARSEDATETIME('00:00', 'HH:mm'), PARSEDATETIME('01:10', 'HH:mm'), 2, 1);
INSERT INTO ROUTE
values (3, PARSEDATETIME('13:14', 'HH:mm'), PARSEDATETIME('22:49', 'HH:mm'), 1, 3);
INSERT INTO ROUTE
values (4, PARSEDATETIME('15:44', 'HH:mm'), PARSEDATETIME('11:29', 'HH:mm'), 3, 4);
INSERT INTO ROUTE
values (5, PARSEDATETIME('11:46', 'HH:mm'), PARSEDATETIME('23:39', 'HH:mm'), 4, 3);
INSERT INTO ROUTE
values (6, PARSEDATETIME('11:47', 'HH:mm'), PARSEDATETIME('10:59', 'HH:mm'), 5, 6);
INSERT INTO ROUTE
values (7, PARSEDATETIME('13:41', 'HH:mm'), PARSEDATETIME('00:29', 'HH:mm'), 9, 10);
INSERT INTO ROUTE
values (8, PARSEDATETIME('12:44', 'HH:mm'), PARSEDATETIME('20:09', 'HH:mm'), 10, 1);
INSERT INTO ROUTE
values (9, PARSEDATETIME('11:34', 'HH:mm'), PARSEDATETIME('02:49', 'HH:mm'), 11, 10);
INSERT INTO ROUTE
values (10, PARSEDATETIME('12:44', 'HH:mm'), PARSEDATETIME('12:41', 'HH:mm'), 11, 12);
INSERT INTO ROUTE
values (11, PARSEDATETIME('14:44', 'HH:mm'), PARSEDATETIME('20:41', 'HH:mm'), 11, 13);
INSERT INTO ROUTE
values (12, PARSEDATETIME('15:14', 'HH:mm'), PARSEDATETIME('02:39', 'HH:mm'), 11, 14);
INSERT INTO ROUTE
values (13, PARSEDATETIME('17:04', 'HH:mm'), PARSEDATETIME('21:29', 'HH:mm'), 11, 15);
INSERT INTO ROUTE
values (14, PARSEDATETIME('17:24', 'HH:mm'), PARSEDATETIME('17:19', 'HH:mm'), 11, 16);
INSERT INTO ROUTE
values (15, PARSEDATETIME('18:54', 'HH:mm'), PARSEDATETIME('02:59', 'HH:mm'), 11, 17);
INSERT INTO ROUTE
values (16, PARSEDATETIME('11:43', 'HH:mm'), PARSEDATETIME('12:09', 'HH:mm'), 12, 11);
INSERT INTO ROUTE
values (17, PARSEDATETIME('18:44', 'HH:mm'), PARSEDATETIME('18:22', 'HH:mm'), 15, 16);
INSERT INTO ROUTE
values (18, PARSEDATETIME('11:41', 'HH:mm'), PARSEDATETIME('22:29', 'HH:mm'), 16, 17);
INSERT INTO ROUTE
values (19, PARSEDATETIME('07:42', 'HH:mm'), PARSEDATETIME('19:29', 'HH:mm'), 17, 2);
INSERT INTO ROUTE
values (20, PARSEDATETIME('19:43', 'HH:mm'), PARSEDATETIME('02:19', 'HH:mm'), 18, 2);
INSERT INTO ROUTE
values (21, PARSEDATETIME('11:47', 'HH:mm'), PARSEDATETIME('22:59', 'HH:mm'), 19, 2);
INSERT INTO ROUTE
values (22, PARSEDATETIME('01:49', 'HH:mm'), PARSEDATETIME('13:19', 'HH:mm'), 20, 11);
INSERT INTO ROUTE
values (23, PARSEDATETIME('11:40', 'HH:mm'), PARSEDATETIME('10:09', 'HH:mm'), 20, 9);
INSERT INTO ROUTE
values (24, PARSEDATETIME('21:40', 'HH:mm'), PARSEDATETIME('10:09', 'HH:mm'), 20, 1);
