server:
  port: ${PORT:8888}

spring:
  application:
    name: registry

logging:
  level:
    org.springframework.cloud.netflix.eureka: TRACE
    org.springframework.cloud.netflix.discovery: OFF

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/